### DISCUSSION TITLE
Minimize Server Sidebar/Names (toggle)

### DISCUSSION THREAD

**Discussion by Pseudoexpertise** [stoatchat/discussions#524] [Feature Suggestions]
Somewhat related to #498
## Suggestion
I suggest the option to customize the appearence of the channel names and channel icons - similar to what you can do with the member list sidebar on the right side
I wrote a little draft for the custom CSS option in advanced settings, that produces a styling as shown in the picture below:
```css
[class^=Category-sc]                  {display: none;} /* creates a conflict with other areas */
[class^=ServerSidebar__ServerBase-sc] {width: 40px;}
[class^=ServerSidebar__ServerList-sc] {padding: 0px;}
```
<img width="198" alt="suggestion" src="https://user-images.githubusercontent.com/128087282/230140640-937cd9a1-5a21-40e1-9886-8d86f9987f28.png">

## Problem
Though this view only becomes convenient when the sidebar with all the other severs disappears.
On the other hand there might be servers where the icons are ugly or misleading. There it would be nice to remove them entirely, being left with three options:
1. The current state, having both, the icons and the names (default)
2. (similar to) What you see in my picture: no names, only icons
3. No icons, only names

Now for option 2 to be convenient we need to remove the sidebar for switching between servers.
And increasing the symbol size might also be a good idea for that particular setting to make the icons easier to click.

I suggest implementing this feature by creating a hover effect, showing a '<' when moving the mouse to either the edge of the window or the edge of the icon sidebar.
By clicking it all the other servers disappear.

There is one last issue for option 2 though:
As the category names disappear you can poorly navigate between them. You could solve this problem by giving the categories their own icons, but that could lead to confusion because you now might forget whether something was a channel or a category.
One way to solve this is by giving the categories their own colors. Or maybe someone finds an even better idea to distinct them
