### DISCUSSION TITLE
Getting error while deploying - address already in use

### DISCUSSION THREAD

**Discussion by DezyNation** [stoatchat/discussions#631] [Q&A] [answered]
I'm trying to deploy Revolt on my VPS using docker. But I'm getting this error

`Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use`

I have also updated my .env file but don't know why it's still considering 0.0.0.0 as HOSTNAME
Here's what I have configured in .env
‎
‎
```
HOSTNAME=revolt.mydomain.com
REVOLT_APP_URL=https://revolt.mydomain.com/
```

I haven't touched the `docker-compose.yml` file.

**Comment by DezyNation** [comment, marked as answer]
I solved it by following the steps for reverse proxy. In your `docker-compose.yml` use any port which is available.

```
# Caddy web server
  caddy:
    image: caddy
    restart: always
    env_file: .env
    ports:
      - "4271:80"
      - "4272:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config
```

And then in your .env, mention the port you are reffering to:
`HOSTNAME=:443`
