### DISCUSSION TITLE
Error after deployment - Client sent an HTTP request to an HTTPS server.

### DISCUSSION THREAD

**Discussion by DezyNation** [stoatchat/discussions#632] [Q&A]
I deployed Revolt on my VPS using Docker. The deployment process seemed to be fine except this error:
`Client sent an HTTP request to an HTTPS server.`

Can anyone please tell me why this would have happened? Here are some related information.

My `.env` file
```
# Hostname used for Caddy
# This should in most cases match REVOLT_APP_URL
HOSTNAME=:443

# URL to where the Revolt app is publicly accessible
REVOLT_APP_URL=https://revolt.mydomain.com
```

My `caddy` configs in `docker-compose.yml` file
```
caddy:
    image: caddy
    restart: always
    env_file: .env
    ports:
      - "4271:80"
      - "4272:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config
```

And finally my NGINX configuration file `revolt.mydomain.com.conf`

```
#Upstreams
upstream revolt {
server 0.0.0.0:4272;
}

# HTTP — redirect all traffic to HTTPS
server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  ssl_certificate_key /etc/letsencrypt/live/revolt.mydomain.com/privkey.pem;
  ssl_certificate /etc/letsencrypt/live/revolt.mydomain.com/fullchain.pem;
  server_name revolt.mydomain.com;

  if ($scheme != "https") {
    rewrite ^ https://$host$uri permanent;
  }

  location ~ /.well-known {
    auth_basic off;
    allow all;
  }

  

  #index index.html
  location / {
    proxy_pass http://revolt;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    
    proxy_pass_request_headers on;
    proxy_max_temp_file_size 0;
    proxy_connect_timeout 900;
    proxy_send_timeout 900;
    proxy_read_timeout 900;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    proxy_temp_file_write_size 256k;
  }
}
```

**Comment by DezyNation** [comment]
Ok since port 443 is already being used so the solution is that you just need to edit your `docker-compose.yml` file like this:

```
caddy:
    image: caddy
    restart: always
    env_file: .env
    ports:
      - "4272"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config
```

You just have to change the port. And make sure you allow all the ports mentioned in `Caddyfile` by running `ufw allow YOUR_PORT_NUMBER`
